routes/web.php
<?php

use App\Http\Controllers\CountryController;
use App\Http\Controllers\RegionController;
use App\Http\Controllers\DttotController;
use \App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->middleware('auth');

Route::middleware(['auth', 'web'])->group(function () {
    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');

    //    Router Country
    Route::resource('country', CountryController::class);
    Route::get('/dataTables', [CountryController::class, 'dataTables'])->name('country-dataTables');


    //    Router Region
    Route::get('/region/dataTables', [RegionController::class, 'dataTablesRegion'])->name('region-dataTables');
    Route::resource('region', RegionController::class);

    //    Router DTTOT
    Route::resource('daftar-dttot', DttotController::class);
    //    Route::get('dataTables', [DttotController::class, 'dataTables'])->name('dttot-dataTables');

});

Auth::routes();



// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Country.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    use HasFactory;
    protected $table = 'countries';
    protected $fillable = ['code_country', 'name_country'];
    protected $guarded = array();


    public function region()
    {
        return $this->hasMany(Country::class);
    }
    public function getData()
    {
        return static::orderBy('created_at', 'desc')->get();
    }

    public function storeData($input)
    {
        return static::create($input);
    }
}

app/Http/Controllers/CountryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Country;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Validator;
use App\Http\Requests\UpdateCountryRequest;
use Barryvdh\Debugbar\Twig\Extension\Debug;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Country $country)
    {

        // dd($data);
        // return DataTables::of($data)
        //     ->addColumn('Actions', function ($data) {
        //         return '<button type="button" class="btn btn-success btn-sm" id="getEditArticleData" data-id="' . $data->id . '">Edit</button>
        //             <button type="button" data-id="' . $data->id . '" data-toggle="modal" data-target="#DeleteArticleModal" class="btn btn-danger btn-sm" id="getDeleteId">Delete</button>';
        //     })
        //     ->rawColumns(['Actions'])
        //     ->make(true);

        // dd($data);
        // DataTables::of($data)
        //     ->addIndexColumn()
        //     ->addColumn('action', function ($data) {
        //         return view('layouts._action', [
        //             'model'      => $data->name,
        //             'urlShow'    => route('country.show', $data->id),
        //             'urlEdit'    => route('country.edit', $data->id),
        //             'urlDestroy' => route('country.destroy', $data->id)
        //         ]);
        //     })
        //     ->rawColumns(['action'])
        //     ->make(true);


        return view('country.country');
    }

    public function getArticles(Request $request, Country $country)
    {
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('country.add-country');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreCountryRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Country $country)
    {
        $validator = Validator::make($request->all(), [
            'code_country' => 'required|max:5',
            'name_country' => 'required',
        ]);


        if ($validator->fails()) {
            return redirect()->back()
                ->with('errorForm', $validator->errors()->getMessages())
                ->withInput();
        }

        try {
            $country->storeData($request->all());
            return redirect()->route('country.index')->with('success', 'Data berhasil disimpan');
        } catch (\Exception $e) {
            Debug::info($e->getMessage());
            return redirect()->back()->with('error', 'Error during the creation!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function show(Country $country)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function edit(Country $country)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateCountryRequest  $request
     * @param  \App\Models\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCountryRequest $request, Country $country)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Country  $country
     * @return \Illuminate\Http\Response
     */
    public function destroy(Country $country)
    {
        //
    }

    public function dataTables(Country $country)
    {
        $data = $country->getData();
        return DataTables::of($data)
            ->addColumn('Actions', function ($data) {
                return '<button type="button" class="btn btn-success btn-sm" id="getEditArticleData" data-id="' . $data->id . '">Edit</button>
                    <button type="button" data-id="' . $data->id . '" data-toggle="modal" data-target="#DeleteArticleModal" class="btn btn-danger btn-sm" id="getDeleteId">Delete</button>';
            })
            ->rawColumns(['Actions'])
            ->make(true);
    }
}

resources/views/country/add-country.blade.php
@extends('layouts.master')
@section('title', 'Data Negara')
@push('style')
    <link rel="stylesheet" href="{{ asset('library/selectric/public/selectric.css') }}">
@endpush
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Tambah Code dan Nama Negara</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="#">Master Data</a></div>
                <div class="breadcrumb-item"><a href="#">Daftar Negara</a></div>
                <div class="breadcrumb-item">Tambah</div>
            </div>
        </div>
        <div class="section-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="card mb-0">
                        <div class="card-header">
                            <h4>Form Input</h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('country.store') }}" method="POST">
                                @csrf
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Kode Negara <sup class="text-danger">*</sup></label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <div class="input-group-text">
                                                        <i class="fas fa-flag"></i>
                                                    </div>
                                                </div>
                                                <input type="text"
                                                    class="form-control @error('code_country') is-invalid @enderror"
                                                    data-indicator="pwindicator" name="code_country" required="" autofocus
                                                    {{ old('code_country') }}>
                                                @error('code_country')
                                                    <div class="invalid-feedback">{{ $message }}</div>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Nama Negara <sup class="text-danger">*</sup></label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <div class="input-group-text">
                                                        <i class="fas fa-globe"></i>
                                                    </div>
                                                </div>
                                                <input type="text"
                                                    class="form-control @error('name_country') is-invalid @enderror"
                                                    name="name_country" required="" value="{{ old('title') }}">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="breadcrumb-item">
                                    <span class=""><sup class="text-danger"><strong>*</strong></sup> Wajib
                                        diisi</span>
                                </div>
                                <div class="card-footer text-right">
                                    <button class="btn btn-primary"><i class="fas fa-save mr-2"></i>Simpan</button>
                                    <a href="{{route('country.index')}}" class="btn btn-secondary"><i class="far fa-arrow-alt-circle-left mr-2"></i>Kembali</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>

@endsection
@push('scripts')

@endpush

resources/views/country/country.blade.php
@extends('layouts.master')
@section('title', 'Data Negara')
@push('style')
    <link rel="stylesheet" href="{{ asset('library/selectric/public/selectric.css') }}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
@endpush
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Daftar Code dan Nama Negara</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="#">Master Data</a></div>
                <div class="breadcrumb-item">Nama Negara</div>
            </div>
        </div>
        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card mb-0">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="section-header-button">
                                        <a href="{{ route('country.create') }}" class="btn btn-primary">Tambah</a>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class=" text-right">
                                        <a href="#" class="btn btn-secondary">CSV</a>
                                        <a href="#" class="btn btn-danger">Excel</a>
                                        <a href="#" class="btn btn-success">PDF</a>
                                        <a href="#" class="btn btn-light">Upload</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {{-- @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif --}}
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-striped datatable">
                                    <thead>
                                        <tr>
                                            <th>Code Negara</th>
                                            <th>Nama Negara</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection
@push('scripts')
    <!-- JS Libraies -->
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    {{-- <script src="{{ asset('library/datatables/media/js/jquery.dataTables.min.js') }}"></script> --}}
    {{-- <script src="{{ asset('library/jquery-ui-dist/jquery-ui.min.js') }}"></script> --}}
    <!-- Page Specific JS File -->
    <script src="{{ asset('assets/js/page/modules-datatables.js') }}"></script>
    <!-- General JS Scripts -->

    <script type="text/javascript">
        $(document).ready(function() {
            var dataTable = $('.datatable').DataTable({
                processing: true,
                serverSide: true,
                autoWidth: false,
                // pageLength: 5,
                // scrollX: true,
                "order": [
                    [0, "desc"]
                ],
                ajax: '{{ route('country-dataTables') }}',
                columns: [{
                        data: 'code_country',
                        name: 'code_country'
                    },
                    {
                        data: 'name_country',
                        name: 'name_country'
                    },
                    {
                        data: 'Actions',
                        name: 'Actions',
                        orderable: false,
                        serachable: false,
                        sClass: 'text-center'
                    },
                ]
            });
        });
    </script>
@endpush