routes/web.php
<?php

use App\Http\Controllers\CountryController;
use App\Http\Controllers\RegionController;
use App\Http\Controllers\DttotController;
use \App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->middleware('auth');

Route::middleware(['auth', 'web'])->group(function () {
    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');

    //    Router Country
    Route::resource('country', CountryController::class);
    Route::get('/dataTables', [CountryController::class, 'dataTables'])->name('country-dataTables');


    //    Router Region
    Route::get('/region/dataTables', [RegionController::class, 'dataTablesRegion'])->name('region-dataTables');
    Route::resource('region', RegionController::class);

    //    Router DTTOT
    Route::resource('daftar-dttot', DttotController::class);
    //    Route::get('dataTables', [DttotController::class, 'dataTables'])->name('dttot-dataTables');

});

Auth::routes();



// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Region.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Region extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     **/
    protected $table = 'regions';
    protected $fillable = [
        'country_id',
        'code_provinsi',
        'nama_provinsi',
        'code_kab',
        'nama_kab',
    ];
    protected $guarded = array();


    public function country()
    {
        return $this->belongsTo(Country::class);
    }

    public function getProvince()
    {
        return static::orderBy('created_at', 'desc')->get();
    }
}

app/Http/Controllers/RegionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Region;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\StoreRegionRequest;
use App\Http\Requests\UpdateRegionRequest;

class RegionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Region $region)
    {
        return view('region.region');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('region.add-region');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreRegionRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRegionRequest $request)
    {
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Region  $region
     * @return \Illuminate\Http\Response
     */
    public function show(Region $region)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Region  $region
     * @return \Illuminate\Http\Response
     */
    public function edit(Region $region)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateRegionRequest  $request
     * @param  \App\Models\Region  $region
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRegionRequest $request, Region $region)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Region  $region
     * @return \Illuminate\Http\Response
     */
    public function destroy(Region $region)
    {
        //
    }

    public function dataTablesRegion(Region $region)
    {
        $data = $region->getProvince();

        // select * from countries c
        // join regions r on r.country_id  = c.id ;

        // $data = Region::join('countries', 'countries.id', '=', 'regions.country_id')
        // ->select('code_provinsi', 'nama_provinsi', 'code_kab', 'nama_katang')
        // ->get();

        // $data = Region::all();
        // $data = DB::table('regiaon')->select('code_provinsi', 'nama_provinsi, code_kab', 'nama_katang')
        //     ->join('countries', 'countries.id', '=', 'regions.country_id')
        //     ->get();
        // $data = Region::select('nama_provinsi', 'code_kab', 'nama_kab')
        // ->join('regions', 'regions.country_id', '=', 'countries.id')
        // ->get();

        return DataTables::of($data)
            ->addColumn('Actions', function ($data) {
                return '<button type="button" class="btn btn-success btn-sm" id="getEditArticleData" data-id="' . $data->id . '">Edit</button>
                    <button type="button" data-id="' . $data->id . '" data-toggle="modal" data-target="#DeleteArticleModal" class="btn btn-danger btn-sm" id="getDeleteId">Delete</button>';
            })
            ->rawColumns(['Actions'])
            ->make(true);
    }
}

resources/views/region/add-region.blade.php
@extends('layouts.master')
@section('title', 'Data Negara')
@push('style')
    <link rel="stylesheet" href="{{ asset('library/selectric/public/selectric.css') }}">
@endpush
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Tambah DTTOT</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="#">Master Data</a></div>
                <div class="breadcrumb-item">Daftar Region</div>
                <div class="breadcrumb-item">Tambah</div>
            </div>
        </div>
        <div class="section-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="card mb-0">
                        <div class="card-header">
                            <h4>Form Input</h4>
                        </div>
                        <div class="card-body">
                            <form action="#" method="POST">
                                @csrf
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Kode Provinsi <sup class="text-danger">*</sup></label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <div class="input-group-text">
                                                        <i class="fas fa-flag"></i>
                                                    </div>
                                                </div>
                                                <input type="text"
                                                       class="form-control @error('code_country') is-invalid @enderror"
                                                       data-indicator="pwindicator" name="code_country" required=""
                                                    {{ old('code_country') }}>
                                                @error('code_country')
                                                <div class="invalid-feedback">{{ $message }}</div>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Nama Provinsi <sup class="text-danger">*</sup></label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <div class="input-group-text">
                                                        <i class="fas fa-globe"></i>
                                                    </div>
                                                </div>
                                                <input type="text"
                                                       class="form-control @error('name_country') is-invalid @enderror"
                                                       name="name_country" required="" value="{{ old('title') }}">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Kode Kabupaten/Kota <sup class="text-danger">*</sup></label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <div class="input-group-text">
                                                        <i class="fas fa-flag"></i>
                                                    </div>
                                                </div>
                                                <input type="text"
                                                       class="form-control @error('code_country') is-invalid @enderror"
                                                       data-indicator="pwindicator" name="code_country" required=""
                                                    {{ old('code_country') }}>
                                                @error('code_country')
                                                <div class="invalid-feedback">{{ $message }}</div>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Nama Kabupaten/Kota <sup class="text-danger">*</sup></label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <div class="input-group-text">
                                                        <i class="fas fa-globe"></i>
                                                    </div>
                                                </div>
                                                <input type="text"
                                                       class="form-control @error('name_country') is-invalid @enderror"
                                                       name="name_country" required="" value="{{ old('title') }}">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Kode Kecamatan<sup class="text-danger">*</sup></label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <div class="input-group-text">
                                                        <i class="fas fa-flag"></i>
                                                    </div>
                                                </div>
                                                <input type="text"
                                                       class="form-control @error('code_country') is-invalid @enderror"
                                                       data-indicator="pwindicator" name="code_country" required=""
                                                    {{ old('code_country') }}>
                                                @error('code_country')
                                                <div class="invalid-feedback">{{ $message }}</div>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Nama Kecamatan<sup class="text-danger">*</sup></label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <div class="input-group-text">
                                                        <i class="fas fa-globe"></i>
                                                    </div>
                                                </div>
                                                <input type="text"
                                                       class="form-control @error('name_country') is-invalid @enderror"
                                                       name="name_country" required="" value="{{ old('title') }}">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="breadcrumb-item">
                                    <span class=""><sup class="text-danger"><strong>*</strong></sup> Wajib
                                        diisi</span>
                                </div>
                                <div class="card-footer text-right">
                                    <button class="btn btn-primary"><i class="fas fa-save mr-2"></i>Simpan</button>
                                    <a href="{{route('region.index')}}" class="btn btn-secondary"><i class="far fa-arrow-alt-circle-left mr-2"></i>Kembali</a>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </section>

@endsection
@push('scripts')

@endpush

resources/views/region/region.blade.php
@extends('layouts.master')
@section('title', 'Data Provinsi dan Kabupaten')
@push('style')
    <link rel="stylesheet" href="{{ asset('library/selectric/public/selectric.css') }}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
@endpush
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Daftar Code dan Nama Negara</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item"><a href="#">Master Data</a></div>
                <div class="breadcrumb-item">Nama Negara</div>
            </div>
        </div>
        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card mb-0">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="section-header-button">
                                        <a href="{{ route('region.create') }}" class="btn btn-primary">Tambah</a>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class=" text-right">
                                        <a href="#" class="btn btn-secondary">CSV</a>
                                        <a href="#" class="btn btn-danger">Excel</a>
                                        <a href="#" class="btn btn-success">PDF</a>
                                        <a href="#" class="btn btn-light">Upload</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {{-- @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif --}}
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-striped datatable">
                                    <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Code Provinsi</th>
                                            <th>Nama Provinsi</th>
                                            <th>Code Kabupaten/Kota</th>
                                            <th>Nama Kabupaten/Kota</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection
@push('scripts')
    <!-- JS Libraies -->
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    {{-- <script src="{{ asset('library/datatables/media/js/jquery.dataTables.min.js') }}"></script> --}}
    {{-- <script src="{{ asset('library/jquery-ui-dist/jquery-ui.min.js') }}"></script> --}}
    <!-- Page Specific JS File -->
    <script src="{{ asset('assets/js/page/modules-datatables.js') }}"></script>
    <!-- General JS Scripts -->

    <script type="text/javascript">
        $(document).ready(function() {
            var dataTable = $('.datatable').DataTable({
                processing: true,
                serverSide: true,
                autoWidth: false,
                // pageLength: 5,
                // scrollX: true,
                "order": [
                    [0, "asc"]
                ],
                ajax: '{{ route('region-dataTables') }}',
                type: "POST",
                columns: [{
                        data: null,
                        orderable: false,
                        searchable: false,
                        render: function(data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        }
                    },
                    {
                        data: 'code_provinsi',
                        name: 'code_provinsi',
                        // className: 'text-center'
                    }, {
                        data: 'nama_provinsi',
                        name: 'nama_provinsi'
                    },
                    {
                        data: 'code_kab',
                        name: 'code_kab'
                    },
                    {
                        data: 'nama_kab',
                        name: 'nama_kab'
                    },
                    {
                        data: 'Actions',
                        name: 'Actions',
                        orderable: false,
                        serachable: false,
                        sClass: 'text-center'
                    },
                ]
            });
        });
    </script>
@endpush