routes/web.php
<?php

use App\Http\Controllers\CountryController;
use App\Http\Controllers\RegionController;
use App\Http\Controllers\DttotController;
use \App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->middleware('auth');

Route::middleware(['auth', 'web'])->group(function () {
    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');

    //    Router Country
    Route::resource('country', CountryController::class);
    Route::get('/dataTables', [CountryController::class, 'dataTables'])->name('country-dataTables');


    //    Router Region
    Route::get('/region/dataTables', [RegionController::class, 'dataTablesRegion'])->name('region-dataTables');
    Route::resource('region', RegionController::class);

    //    Router DTTOT
    Route::resource('daftar-dttot', DttotController::class);
    //    Route::get('dataTables', [DttotController::class, 'dataTables'])->name('dttot-dataTables');

});

Auth::routes();



// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/nasabah/add-dttot.blade.php
@extends('layouts.master')
@section('title', 'Data Negara')
@push('style')
<link rel="stylesheet" href="{{ asset('library/selectric/public/selectric.css') }}">
@endpush
@section('content')
<section class="section">
    <div class="section-header">
        <h1>Tambah Data Nasabah</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
            <div class="breadcrumb-item"><a href="#">Master Data</a></div>
            <div class="breadcrumb-item">Daftar Nasabah</div>
            <div class="breadcrumb-item">Tambah</div>
        </div>
    </div>
    <div class="section-body">
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-0">
                    <div class="card-header">
                        <h4>Form Input</h4>
                    </div>
                    <div class="card-body">
                        <form action="#" method="POST">
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Nama <sup class="text-danger">*</sup></label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">
                                                    <i class="fas fa-flag"></i>
                                                </div>
                                            </div>
                                            <input type="text"
                                                class="form-control @error('code_country') is-invalid @enderror"
                                                data-indicator="pwindicator" name="code_country" required=""
                                                {{ old('code_country') }}>
                                            @error('code_country')
                                            <div class="invalid-feedback">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>NIK <sup class="text-danger">*</sup></label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">
                                                    <i class="fas fa-globe"></i>
                                                </div>
                                            </div>
                                            <input type="text"
                                                class="form-control @error('name_country') is-invalid @enderror"
                                                name="name_country" required="" value="{{ old('title') }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Tempat Tanggal Lahir <sup class="text-danger">*</sup></label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">
                                                    <i class="fas fa-flag"></i>
                                                </div>
                                            </div>
                                            <input type="text"
                                                class="form-control @error('code_country') is-invalid @enderror"
                                                data-indicator="pwindicator" name="code_country" required=""
                                                {{ old('code_country') }}>
                                            @error('code_country')
                                            <div class="invalid-feedback">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Alamat <sup class="text-danger">*</sup></label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">
                                                    <i class="fas fa-globe"></i>
                                                </div>
                                            </div>
                                            <input type="text"
                                                class="form-control @error('name_country') is-invalid @enderror"
                                                name="name_country" required="" value="{{ old('title') }}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="breadcrumb-item">
                                <span class=""><sup class="text-danger"><strong>*</strong></sup> Wajib
                                    diisi</span>
                            </div>
                            <div class="card-footer text-right">
                                <button class="btn btn-primary"><i class="fas fa-save mr-2"></i>Simpan</button>
                                <a href="{{route('daftar-dttot.index')}}" class="btn btn-secondary"><i
                                        class="far fa-arrow-alt-circle-left mr-2"></i>Kembali</a>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>

    </div>
</section>

@endsection
@push('scripts')

@endpush

resources/views/nasabah/dttot.blade.php
@extends('layouts.master')
@section('title', 'Daftar Nasabah')

@push('style')
{{--    <link rel="stylesheet" href="{{ asset('library/selectric/public/selectric.css') }}">--}}
{{--    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">--}}
@endpush

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Daftar Nasabah</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
            <div class="breadcrumb-item"><a href="#">Master Data</a></div>
            <div class="breadcrumb-item">Daftar Nasabah</div>
        </div>
    </div>
    <div class="section-body">
        <div class="row">
            <div class="col-12">
                <div class="card mb-0">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="section-header-button">
                                    <a href="{{ route('daftar-dttot.create') }}" class="btn btn-primary">Tambah</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {{-- @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
            </div>
            @endif --}}
        </div>
    </div>
    </div>
    <div class="row mt-3">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped datatable table-hover table-responsive">
                            <thead>
                                <tr>
                                    <th>Nama</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th>fina</th>
                                    <td>Mark</td>
                                    <td>Otto</td>
                                </tr>
                                <tr>
                                    <th>Ahmad</th>
                                    <td>Mark</td>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>
@endsection

@push('script') @endpush